name: Logging Mutants

# only run on push in order to update the cache output
# flow:
# restore cache
# install cargo-mutants crate in order to run the 'cargo mutants' command
# create a file with the current commit hash if a previous one doesn't exist, then print it
# run the script that handles the 'cargo mutants' command on the differences between the latest updates and the last commit where it was ran
# overwrite the previous commit hash with the current one for the following run
# delete the old cache
# save the new cache with the updated mutants
inputs:
  gh-token:
    description: 'The github token secret in order to delete the old cache'
    required: true
    default: ''

runs:
  using: 'composite'

  steps:
    - name: Check Cache
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      id: check_cache
      with:
        lookup-only: true
        path: ./
        key: mutants-stable-${{ github.ref_name }}

    - name: Upload initial outputs if there is no cache
      if: steps.check_cache.outputs.cache-hit != 'true'
      uses: stacks-network/actions/mutation-testing/upload-initial-cache@main

    - name: Update cache if we have one available
      if: steps.check_cache.outputs.cache-hit == 'true'
      uses: stacks-network/actions/mutation-testing/update-cache@main
      with:
        gh-token: ${{ inputs.gh-token }}
