name: "Stacks Blockchain Test Environment"
description: "Stacks Blockchain Test Environment"
branding:
  icon: "archive"
  color: "gray-dark"

inputs:
  genesis:
    description: "Restore genesis archive"
    required: false
    default: "false"
  btc-version:
    description: "Bitcoin version"
    required: false
    default: "0.20.0"

runs:
  using: "composite"
  steps:
    ## cleanup runner
    - name: Cleanup Runner
      id: runner_cleanup
      uses: stacks-network/actions/cleanup/disk@main

    ## Checkout the code
    - name: Checkout the latest code
      id: git_checkout
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    ## Install rust toolchain (llvm-tools-preview)
    - name: Setup Rust Toolchain
      id: setup_rust_toolchain
      uses: actions-rust-lang/setup-rust-toolchain@b113a30d27a8e59c969077c0a0168cc13dab5ffc # v1.8.0
      with:
        toolchain: stable
        components: llvm-tools-preview
        cache: false

    ## Restore cargo cache data
    - name: Restore Cargo Cache
      id: restore_cargo_cache
      uses: stacks-network/actions/stacks-core/cache/cargo@main
      with:
        action: restore

    ## Restore nextest target cache data
    - name: Restore Target Cache
      id: restore_target_cache
      uses: stacks-network/actions/stacks-core/cache/target@main
      with:
        action: restore

    ## Restore bitcoin cache data
    - name: Restore Bitcoin Binary Cache
      id: restore_bitcoin_cache
      uses: stacks-network/actions/stacks-core/cache/bitcoin@main
      with:
        action: restore
        btc-version: ${{ inputs.btc-version }}

    ## Symlink bitoind to $PATH
    - name: Link Bitcoin Binary
      id: bitcoin_binary
      shell: bash
      run: |
        sudo ln -s ~/bitcoin/bin/bitcoind /bin/
        ls -al /bin/bitcoind

    ## Restore nextest test archive cache data
    - name: Restore Test Archive Cache
      if: |
        inputs.genesis != 'true'
      id: restore_test_cache
      uses: stacks-network/actions/stacks-core/cache/test-archive@main
      with:
        action: restore

    ## Restore nextest genesis test archive cache data
    - name: Restore Genesis Test Archive Cache
      if: |
        inputs.genesis == 'true'
      id: restore_genesis_test_cache
      uses: stacks-network/actions/stacks-core/cache/genesis-test-archive@main
      with:
        action: restore
