name: "Stacks Blockchain Test Environment"
description: "Stacks Blockchain Test Environment"
branding:
  icon: "archive"
  color: "gray-dark"

inputs:
  genesis:
    description: "Restore genesis archive"
    required: false
    default: "false"
  btc-version:
    description: "Bitcoin version"
    required: false
    default: "0.20.0"

runs:
  using: "composite"
  steps:
    ## cleanup runner
    - name: Cleanup Runner
      id: runner_cleanup
      uses: stacks-network/actions/cleanup/disk@chore/update-actions-versions

    ## Checkout the code
    - name: Checkout the latest code
      id: git_checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    ## Install rust toolchain (llvm-tools-preview)
    - name: Setup Rust Toolchain
      id: setup_rust_toolchain
      uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
      with:
        toolchain: stable
        components: llvm-tools-preview
        cache: false

    ## Restore cargo cache data
    - name: Restore Cargo Cache
      id: restore_cargo_cache
      uses: stacks-network/actions/stacks-core/cache/cargo@chore/update-actions-versions
      with:
        action: restore

    ## Restore nextest target cache data
    - name: Restore Target Cache
      id: restore_target_cache
      uses: stacks-network/actions/stacks-core/cache/target@chore/update-actions-versions
      with:
        action: restore

    ## Restore bitcoin cache data
    - name: Restore Bitcoin Binary Cache
      id: restore_bitcoin_cache
      uses: stacks-network/actions/stacks-core/cache/bitcoin@chore/update-actions-versions
      with:
        action: restore
        btc-version: ${{ inputs.btc-version }}

    ## Symlink bitoind to $PATH
    - name: Link Bitcoin Binary
      id: bitcoin_binary
      shell: bash
      run: |
        sudo ln -s ~/bitcoin/bin/bitcoind /bin/
        ls -al /bin/bitcoind

    ## Restore nextest test archive cache data
    - name: Restore Test Archive Cache
      if: |
        inputs.genesis != 'true'
      id: restore_test_cache
      uses: stacks-network/actions/stacks-core/cache/test-archive@chore/update-actions-versions
      with:
        action: restore

    ## Restore nextest genesis test archive cache data
    - name: Restore Genesis Test Archive Cache
      if: |
        inputs.genesis == 'true'
      id: restore_genesis_test_cache
      uses: stacks-network/actions/stacks-core/cache/genesis-test-archive@chore/update-actions-versions
      with:
        action: restore
