name: "Create Downstream PR"
description: "Create Downstream PR"
branding:
  icon: "git-pull-request"
  color: "gray-dark"

inputs:
  token:
    description: "GH_TOKEN"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout the latest code
      id: git_checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 1

    - name: Create PR
      id: create-pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |

        SOURCE_BRANCH=${{ github.ref_name }} # use the source branch that called this workflow
        TARGET_BRANCH=""
        COMMIT_HASH=$(git log -1 '--pretty=%H') # retrieve the branch commit hash (used to determine who to assign the PR to)

        ## set target branch depending on SOURCE_BRANCH
        case $SOURCE_BRANCH in
          develop)
            TARGET_BRANCH="next"
            ;;
          master)
            TARGET_BRANCH="develop"
            ;;
          *)
            exit 1
            ;;
        esac

        echo "SOURCE_BRANCH: ${SOURCE_BRANCH}"
        echo "TARGET_BRANCH: ${TARGET_BRANCH}"
        echo "COMMIT_HASH: ${COMMIT_HASH}"

        # ## Check if the target branch exists
        echo "LINE 51 check diff"
        echo "run cmd: git ls-remote --exit-code --quiet --heads origin ${TARGET_BRANCH}"
        if ! git ls-remote --exit-code --quiet --heads origin ${TARGET_BRANCH}; then
            echo "LINE 54"
            cat <<EOF >> $GITHUB_STEP_SUMMARY
        Target Branch (\`${TARGET_BRANCH}\`) does not exist.
        EOF
        echo "LINE 58 exiting 1"
        exit 1
        fi

        ## Check diff of source with the target branch origin
        echo "LINE 63 check diff"
        echo "run cmd: git diff origin/${TARGET_BRANCH} --quiet --exit-code > /dev/null 2&>1; echo \$?"
        git diff origin/${TARGET_BRANCH}
        echo "LINE 65 BRANCH_DIFF"
        BRANCH_DIFF=$(git diff origin/${TARGET_BRANCH} --quiet --exit-code > /dev/null 2&>1; echo $?)
        # git diff --name-only origin/main origin/${GITHUB_HEAD_REF}
        # git diff --name-only origin/${TARGET_BRANCH} origin/${SOURCE_BRANCH}
        ## if the diff return code is 0, no files have changed and we can exit successfully
        echo "LINE 68 BRANCH_DIFF: ${BRANCH_DIFF}"
        EXIT_CODE=0
        git diff origin/${TARGET_BRANCH}
        if [ "${BRANCH_DIFF}" -ne "1" ]; then
          echo "LINE 71 - branch_diff: ${BRANCH_DIFF} (!= 1)"
          MSG=""
          echo "branch_diff (${BRANCH_DIFF} != 1 - no PR should be created"
          case $BRANCH_DIFF in
            0)
              echo "LINE 76 branch_diff:${BRANCH_DIFF} (0)"
              MSG="No changes detected between \`${SOURCE_BRANCH}\`->\`${TARGET_BRANCH}\`"
              EXIT_CODE=1
              ;;
            128)
              echo "LINE 81 branch_diff:${BRANCH_DIFF} (128)"
              MSG="Target branch (\`${TARGET_BRANCH}\`) not found"
              EXIT_CODE=2
              ;;
            *)
              echo "LINE 86 branch_diff:${BRANCH_DIFF}"
              MSG="Unknown error code"
              EXIT_CODE=3
              ;;
          esac
        fi

        if [ "${BRANCH_DIFF}" -eq "1" ];then
          echo "LINE 94 getting last commit uid"
          ## using the commit_hash, retrieve the username of the last commit to assign the PR
          ASSIGNED=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/commits/${COMMIT_HASH}" | jq -r .author.login
          )
          echo "LINE 101 ASSIGNED: $ASSIGNED"
          ## Finally, create the PR
          echo "LINE 103 create the PR"
          PR=$(
            gh pr create \
              --assignee "${ASSIGNED}" \
              --head "${SOURCE_BRANCH}" \
              --base "${TARGET_BRANCH}" \
              --title "Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}" \
              --body "Automatic PR to Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}"
          )
          echo "LINE 112"
          PR_NUM=$(basename "$PR")
          echo "LINE 114 PR_NUM=${PR_NUM}"
          MSG="PR [$PR_NUM]($PR) created and assigned to [$ASSIGNED](https://github.com/${ASSIGNED})"
        fi
        cat <<EOF >> $GITHUB_STEP_SUMMARY
        $MSG
        EOF
        echo "LINE 120 MSG: $MSG"
        echo "LINE 121 exiting $EXIT_CODE"
        exit $EXIT_CODE
