name: "Create Downstream PR"
description: "Create Downstream PR"
branding:
  icon: "archive"
  color: "gray-dark"

inputs:
  token:
    description: "GH_TOKEN"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout the latest code
      id: git_checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Create PR
      id: create-pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        SOURCE_BRANCH=${{ github.ref_name }}
        TARGET_BRANCH=""
        ASSIGNED=$(git log -1 '--pretty=%aN')
        case $SOURCE_BRANCH in
          develop)
            TARGET_BRANCH="next"
            ;;
          master)
            TARGET_BRANCH="develop"
            ;;
          *)
            exit 1
            ;;
        esac
        echo "Automatic PR to Merge ${SOURCE_BRANCH} into ${TARGET_BRANCH}"
        echo "Assigned to: $ASSIGNED"
        gh pr create \
          --assignee "${ASSIGNED}" \
          --base "${TARGET_BRANCH}" \
          --title "Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}" \
          --body "Automatic PR to Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}"
        # gh_pr_up() { gh pr create $* || gh pr edit $* }
        # gh_pr_up --title "My pull request" --body "Description"
