name: "Rust Toolchain"
description: "Installs Rust toolchain with optional components"
branding:
  icon: "check-square"
  color: "yellow"

inputs:
  components:
    description: "Rust toolchain components to install"
    required: false
    default: ""
  rust-toolchain:
    description: "Rust toolchain to use"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout the latest code
      id: git_checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Define Rust Toolchain
      shell: bash
      id: define_rust_toolchain
      run: |
        if [ ${{ inputs.rust-toolchain }} != "" ]; then
          echo "RUST_TOOLCHAIN=${{ inputs.rust-toolchain }}" >> $GITHUB_ENV
          exit 0
        else
          echo "RUST_TOOLCHAIN=$(cat ./rust-toolchain)" >> $GITHUB_ENV
        fi

    - name: Setup Rust Toolchain
      id: setup_rust_toolchain
      uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
      with:
        toolchain: ${{ env.RUST_TOOLCHAIN || 'stable' }}
        components: ${{ inputs.components }}
        cache: false
