## Github workflow to create and upload github releases
name: Create Releases
description: "Create GitHub Releases"
branding:
    icon: "archive"
    color: "gray-dark"

inputs:
    node_tag:
        description: "Node Release Tag"
        required: true
    signer_tag:
        description: "Signer Release Tag"
        required: true
    GH_TOKEN:
        description: "GitHub Token"
        required: true

runs:
    using: "composite"
    steps:
        ## Creates the node release
        - name: Create Node Release
          if: |
              inputs.node_tag != ''
          id: create_node_release
          uses: wileyj/actions/stacks-core/release/create-github-release@chore/6601_pr_comment
          # uses: stacks-network/actions/stacks-core/release/create-github-release@main
          with:
              tag: ${{ inputs.node_tag }}
              GH_TOKEN: ${{ inputs.GH_TOKEN }}
              release_type: stacks-core

        ## Creates the signer release
        - name: Create Signer Release
          if: |
              inputs.signer_tag != ''
          id: create_signer_release
          uses: wileyj/actions/stacks-core/release/create-github-release@chore/6601_pr_comment
          # uses: stacks-network/actions/stacks-core/release/create-github-release@main
          with:
              tag: ${{ inputs.signer_tag }}
              GH_TOKEN: ${{ inputs.GH_TOKEN }}
              release_type: stacks-signer
