name: "Run Tests"
description: "Run Tests"
branding:
  icon: "archive"
  color: "gray-dark"

inputs:
  test-name:
    description: "Test name to run"
    required: true
  threads:
    description: "Number of test threads"
    required: false
    default: "num-cpus"
  archive-file:
    description: "Archive file to use for tests"
    required: true
    default: "~/test_archive.tar.zst"
  failure-output:
    description: "Failure output"
    required: false
    default: "final"
  success-output:
    description: "Success output"
    required: false
    default: "never"
  status-level:
    description: "Output status level"
    required: false
    default: "fail"
  retries:
    description: "Number of test retries"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Run Tests
      id: run-tests
      shell: bash
      run: |
        export LLVM_PROFILE_FILE="test-results-%p-%m.profraw" && \
        cargo nextest run \
          --archive-file ${{ inputs.archive-file }} \
          ${{ inputs.threads == '1' && '--no-capture' || format('--test-threads {0}', inputs.threads) }} \
          --retries ${{ inputs.retries }} \
          --run-ignored all \
          --fail-fast \
          ${{ inputs.threads != '1' && format('--failure-output {0}', inputs.failure-output) || '' }} \
          ${{ inputs.threads != '1' && format('--success-output {0}', inputs.success-output) || '' }} \
          --status-level ${{ inputs.status-level }} \
          -E "test(=${{ inputs.test-name }})"
