## Github workflow to check that all jobs parsed as input from 'needs' are successful
name: Check Jobs Status

inputs:
  jobs:
    description: "A list of jobs from the `needs` context."
    required: true
  summary_print:
    description: "Print jobs status to GitHub Step Summary"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Check Jobs
      id: check_jobs
      shell: bash
      run: |
        # Check the jobs status and print the failures
        failing_jobs=()

        # Function to print output to GitHub Step Summary
        print_to_step_summary() {
          echo "## Jobs Status" >> "$GITHUB_STEP_SUMMARY"

          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "Some jobs that are required to succeed have failed." >> "$GITHUB_STEP_SUMMARY"

          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "### Failed Jobs:" >> "$GITHUB_STEP_SUMMARY"

          for job in "${failing_jobs[@]}"; do
            echo "- **$job**" >> "$GITHUB_STEP_SUMMARY"
          done
        }

        # Check that 'jq' command exists
        if ! command -v jq > /dev/null 2>&1; then
          echo "jq command doesn't exist!";
          exit 1;
        fi

        # Search for failures and append them to a list
        for job_name in $(echo '${{ inputs.jobs }}' | jq -r 'keys[]'); do
          result=$(echo '${{ inputs.jobs }}' | jq -r ".[\"$job_name\"].result")
          if [[ "$result" == "failure" ]]; then
            failing_jobs+=("$job_name")
          fi
        done

        # If there is no failing job, exit
        if [[ ${#failing_jobs[@]} -eq 0 ]]; then
          echo "All jobs were successful!"
          exit 0
        fi

        # Print failing jobs to console
        echo "Required jobs failed:"
        for job in "${failing_jobs[@]}"; do
          echo "- $job"
        done

        # If the 'summary_print' input is true, print jobs to GitHub Step Summary, then fail the job
        if [[ "${{ inputs.summary_print }}" == "true" ]]; then
          print_to_step_summary
        fi
        exit 1
