## Github workflow to create and upload a github release
name: Create Release
description: "Create GitHub Release"
branding:
  icon: "archive"
  color: "gray-dark"

inputs:
  tag:
    description: "Release Tag"
    required: true
  # docker_tag:
  #   description: "Release Docker Tag"
  #   required: true
  GH_TOKEN:
    description: "GitHub Token"
    required: true

runs:
  using: "composite"
  steps:
    ## Downloads the artifacts built in `create-source-binary`
    - name: Download Artifacts
      id: download_artifacts
      # uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        # pattern: ${{ inputs.docker_tag }}-binary-build-*
        pattern: ${{github.sha}}-* # matches artifact names like 727043a37fbc90f1c7eb391b590bde460ca0e36a-linux-glibc-arm64
        path: release
        merge-multiple: true

    ## Generate a checksums file to be added to the release page
    - name: Generate Checksums
      id: generate_checksum
      uses: stacks-network/actions/generate-checksum@main
      with:
        artifact_download_pattern: "${{github.sha}}-${{ inputs.release_type }}*" # matches artifact names like 727043a37fbc90f1c7eb391b590bde460ca0e36a-linux-glibc-arm64
        # artifact_download_pattern: "${{ inputs.docker_tag }}-binary-build-*"

    ## Upload the release archives with the checksums file
    - name: Upload Release
      id: upload_release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
      with:
        name: "Release ${{ inputs.tag || github.ref }}"
        tag_name: ${{ inputs.tag || github.ref }}
        draft: true
        prerelease: true
        fail_on_unmatched_files: true
        target_commitish: ${{ github.sha }}
        generate_release_notes: false
        files: |
          release/*.zip
          CHECKSUMS.txt
